export const GET_DATA_OVERTIME_SUCCESS = 'GET_DATA_OVERTIME_SUCCESS';
export const GET_DATA_OVERTIME_FAILURE = 'GET_DATA_OVERTIME_FAILURE';
export const CREATE_DATA_OVERTIME_SUCCESS = 'CREATE_DATA_OVERTIME_SUCCESS';
export const CREATE_DATA_OVERTIME_FAILURE = 'CREATE_DATA_OVERTIME_FAILURE';
export const DELETE_DATA_OVERTIME_SUCCESS = 'DELETE_DATA_OVERTIME_SUCCESS';
export const DELETE_DATA_OVERTIME_FAILURE = 'DELETE_DATA_OVERTIME_FAILURE';
